In [2]:
import numpy as np
from hmmlearn import hmm
import math

# 定义N
states = ["coin1", "coin2", "coin3"]
n_states = len(states)  # 获取状态个数

# 定义M
observations = ["Head", "Tail"]
n_observations = len(observations)  # 获取观测个数

# 定义pi
start_probability = np.array([0.3, 0.3, 0.4])

# 定义A
transition_probability = np.array([
  [0.5, 0.45, 0.05],
  [0.45, 0.1, 0.45],
  [0.45, 0.45, 0.1]
])

# 定义B
emission_probability = np.array([
  [0.5, 0.5],
  [0.75, 0.25],
  [0.25, 0.75]
])
# 建立HMM模型，共有n_states个隐状态
model = hmm.MultinomialHMM(n_components=n_states)
# HMM模型赋值
model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability

MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


In [3]:
# 解码问题
seen = np.array([[0, 0, 1, 0, 1, 1]]).T
logprob, coin = model.decode(seen, algorithm="viterbi")
print(coin)

ValueError: n_trials must be set

In [4]:
# 评估问题
probability = model.score(seen)
print(math.e**probability)

ValueError: n_trials must be set

In [5]:
import numpy as np
from hmmlearn import hmm
import math

states = ["coin1", "coin2", "coin3"]
n_states = len(states)

observations = ["Head", "Tail"]
n_observations = len(observations)
model = hmm.MultinomialHMM(n_components=n_states, n_iter=20, tol=0.01)
# n_inter: 要执行的最大迭代数
# tol: 收敛阈值。如果log-likelihood的增益低于这个值，EM就会停止。

MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


In [7]:
# 观测序列
X = np.array([[0, 0, 1, 0, 1, 1]])
# 模型训练
model.fit(X)
print(model.startprob_)
print(model.transmat_)
print(model.emissionprob_)
print(math.e**model.score(X))

Fitting a model with 23 free scalar parameters with only 6 data points will result in a degenerate solution.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.
Some rows of transmat_ have zero sum because no transition from the state was ever observed.


[0.00730786 0.12896642 0.86372572]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.         0.         0.33333333 0.         0.33333333 0.33333333]
 [0.         0.         0.33333333 0.         0.33333333 0.33333333]
 [0.         0.         0.33333333 0.         0.33333333 0.33333333]]


ValueError: transmat_ rows must sum to 1 (got row sums of [0. 0. 0.])